const type=new URLSearchParams(location.search).get("game")||"quick";
const cfg={odd:{name:"Odd If Cricket",rules:"1 wicket • no fixed overs",w:1,b:null},quick:{name:"Quick Cricket",rules:"5 wickets • 10 overs",w:5,b:60},real:{name:"Real Cricket",rules:"10 wickets • 20 overs",w:10,b:120}}[type];
let score=0,wickets=0,balls=0,target=null,innings=1,batting=true,over=false;
title.textContent=cfg.name;rules.textContent=cfg.rules;
function upd(){document.getElementById("score").textContent=score+"/"+wickets;document.getElementById("overs").textContent=cfg.b===null?balls:Math.floor(balls/6)+"."+balls%6;document.getElementById("target").textContent=target??"—";}
function toss(c){const x=Math.random()<.5?"Heads":"Tails";const win=c===x;tossResult.textContent="Coin: "+x+". "+(win?"You won the toss!":"Computer won the toss.");if(win)decision.classList.remove("hidden");else start(Math.random()<.5);}
function choose(x){start(x==="bat")}
function start(pb){batting=pb;toss.classList.add("hidden");match.classList.remove("hidden");if(batting)startPlayer();else computerFirst();}
function startPlayer(){message.textContent="Your innings — play";controls.innerHTML=type==="odd"?oddButtons():normalButtons();upd();}
function oddButtons(){return `<div class="buttons hands"><button onclick="hand(1)">☝️<small>1 RUN</small></button><button onclick="hand(2)">✌️<small>2 RUNS</small></button><button onclick="hand(3)">🤟<small>3 RUNS</small></button><button onclick="hand(4)">🖖<small>4 RUNS</small></button><button onclick="hand(5)">🖐️<small>5 RUNS</small></button><button onclick="hand(6)">👍<small>6 RUNS</small></button><button onclick="hand(0)">✊<small>DEFENCE</small></button></div>`}
function normalButtons(){return `<div class="buttons hands"><button onclick="shot(0)">DEFENCE</button><button onclick="shot(1)">1 RUN</button><button onclick="shot(2)">2 RUNS</button><button onclick="shot(3)">3 RUNS</button><button onclick="shot(4)">4 RUNS</button><button onclick="shot(6)">6 RUNS</button></div>`}
function computerFirst(){let cs=0,cw=0;if(type==="odd"){cs=Math.floor(Math.random()*30)+1;cw=1}else for(let i=0;i<cfg.b;i++){if(cw>=cfg.w)break;if(Math.random()<.1)cw++;else cs+=[0,1,1,2,2,3,4,6][Math.floor(Math.random()*8)]}target=cs+1;innings=2;score=0;wickets=0;balls=0;batting=true;message.textContent=`Computer scored ${cs}/${cw}. Target ${target}. Your innings.`;controls.innerHTML=type==="odd"?oddButtons():normalButtons();upd();}
function shot(r){if(over||!batting)return;balls++;if(Math.random()<.12){wickets++;message.textContent="Wicket!"}else{score+=r;message.textContent=r?`${r} run${r>1?"s":""}!`:"Defence."}upd();check()}
function hand(r){if(over||!batting)return;balls++;const c=Math.floor(Math.random()*6)+1;if(r===c){wickets=1;upd();return end("You're out! Final score "+score+"/1.")}if(r===0)message.textContent=`Defence. Computer chose ${c}.`;else{score+=r;message.textContent=`${r} run${r>1?"s":""}. Computer chose ${c}.`}upd();check()}
function check(){if(innings===2&&score>=target)return end("🏆 You won!");if(wickets>=cfg.w||(cfg.b!==null&&balls>=cfg.b)){if(innings===1){target=score+1;innings=2;score=0;wickets=0;balls=0;message.textContent=`Computer scored first innings. Target ${target}. Your chase.`;upd()}else end(score>=target?"🏆 You won!":"Computer won!")}}
function end(x){over=true;message.textContent=x;document.querySelectorAll("button").forEach(b=>b.disabled=true)}upd();